### PR TITLE
Bug Fix - Scrolling issues

### PR DESCRIPTION
**Pull request by DaceyTom2**
### Description
Prototyping scroll issue in mobile

### Additional Notes
WIP - Do not merge

### CODE REVIEW

**Comment by TishamIslam** [comment]
Not 100% sure what this PR is supposed to resolve, I remember that it fixes that weird header scrolling issue but I don't recall the rest of it/if there is more to it.

**Comment by DaceyTom2** [comment]
@TishamIslam That is all it is intended to fix. It is easier to see the issue on mobile when scrolling through chat messages

**Comment by TishamIslam** [comment]
I can't seem to reproduce the bug on mobile, but I managed to do it pretty easily on desktop. Seems to be fixed in this PR but I feel like I'm missing something somehow.

**Comment by DaceyTom2** [comment]
Want a demo?

**Comment by TishamIslam** [comment]
Sure. [https://meet.google.com/gee-eiod-zkb](https://meet.google.com/gee-eiod-zkb)

**Review by TishamIslam — APPROVED** [review]
Works great!

**Pull request merged**
