### PR TITLE
Vcon 60 loading state

### PR DESCRIPTION
**Pull request by DaceyTom2**
Description

For this PR I have the loading state forced. It will have to be removed after Thomas reviews the design and before merging.

### CODE REVIEW

**Comment by neilmispelaar** [comment]
This works perfectly for the demo - so not recommending any changes - my only feedback is that the check on `v-if="inboxItems.length === 0"` to determine loading state would be risky in a more robust environment because what if an inbox really did only have 0 items (ah the dream of Inbox Zero - I have yet to experience thee).

A more robust approach // albeit require more code, would be to have the vuex store keep a `loading` state flag and then when the app is initialized the loading flag is set to true, and then when all the vuex store init functions are completed the loading state is set to false. 

Components then could do something like:
 
```
<template>
<div v-if="loaded === false">
...
</div>
<div v-else>
...
</div>
</template>
<script>
import { reactive } from 'vue';
...
setup() { 

  // Setup local reactive elements
  const localState = reactive({
    loaded: null,
  });
  
  localState.loaded = computed(() => store.getters["inbox/getLoadingState"]);

  return { 
  ...toRefs(localState),
  }
}
</script>
```

This could further be enhanced with an `error` state as well, but that's super overkill for now.

**Comment by neilmispelaar** [comment]
My only other feedback is that - it would be cool to be able to use tailwindcss `annimate-pulse` class but I'll let Thomas Hoy pipe in on design

https://user-images.githubusercontent.com/9325038/123473485-a09fcc00-d5c6-11eb-96d1-a07825ef5bf5.mov

**Review by TishamIslam — COMMENTED** [review]
It's looking really good so far! I don't think there's any issues from what I can tell, but I'd like to give it a more thorough review and do a bit of local testing before approving this.

**Comment by neilmispelaar** [comment]
This looks amazing! 

Love it all. I know I'm not on the approval list but it looks great to me!

One opportunity to improvement for code readability in `Inbox.vue`:

- Separate the loading presentation markup from the actual data populated area 
- Someone quickly reading the code might miss that the `h1` is written just after a loading state check
- Organizing the code into two blocks (one for loading, and one for loaded) would help when someone is scanning the code
- In the future adding an error state might also be easier because the different views are separated 

```
<template>
  <!-- Loading State --> 
  <div v-if="!inboxLoaded">
    ... all loading markup ...
  </div>

  <!-- Loaded State --> 
  <div v-else>
    ... all loaded markup ...
  </div>
</template>
```

In the future we can also look at adding the aria roles I'll make a separate ticket for that because: complicated

**Comment by TishamIslam** [comment]
Aside from what Neil mentioned above, I think it's perfect!

**Review by TishamIslam — APPROVED** [review]

**Review by shewood — CHANGES_REQUESTED** [review]
I love the animation. it looks awesome.
I am concerned that there is no content though and once this gets merged the app will no longer function? or will you add a fix just before merging?

**Comment by DaceyTom2** [comment]
@shewood I have initialise temporarily commented out but will remove before merging. This is so we can view changes on netlify

**Comment by DaceyTom2** [comment]
@neilmispelaar Index is updated to be more readable. Good thinking!

**Review by shewood — APPROVED** [review]
Looks great!

**Pull request merged**
