### PR TITLE
try to fix border thickness

### PR DESCRIPTION
**Pull request by TishamIslam**
## Description
Quick fix to solve the input field issue, not 100% sure if it works on all mobile platforms but the deploy preview on my iPhone 7 
no longer has the weird extra-thick line on it.
[Source](https://stackoverflow.com/questions/54763835/how-to-avoid-an-extra-border-top-thickness-on-bootstrap-input-field-in-iphone)

### CODE REVIEW

**Review by DaceyTom2 — CHANGES_REQUESTED** [review]
This can be done using tailwind.

Checkout https://tailwindcss.com/docs/background-clip

**Comment by TishamIslam** [comment]
Lol thought it was too specific of a thing to be included in tailwind... guess I shouldn't make any assumptions :P

**Comment by DaceyTom2** [comment]
Haha I would have thought as well. If it wasn't for your pr and my confusion on the subject I would have assumed no

**Review by DaceyTom2 — APPROVED** [review]
Beautiful

**Pull request merged**
