### PR TITLE
Removed TheSkipNav

### PR DESCRIPTION
**Pull request by DaceyTom2**
### Description
Removed unused code

### CODE REVIEW

**Comment by TishamIslam** [comment]
This is needed as per [WCAG 2.4.1](https://www.w3.org/WAI/WCAG21/quickref/#bypass-blocks), you can only access it through focusing on it by tabbing, after which it becomes visible.

**Comment by DaceyTom2** [comment]
You are going to have to show me where this is used. My mind is blown

**Comment by neilmispelaar** [comment]
Screen Shot 2021-08-02 at 11 28 37 AM

Screen Shot 2021-08-02 at 11 28 32 AM

**Comment by neilmispelaar** [comment]
I can't recommend the removal of SkipNav links but I can add that the focus styles weren't added in (I think the boilerplate just had the hidden links)

**Comment by TishamIslam** [comment]
I can't send the screen recording here but I'll it send it to you on slack as well, Neil.

**Comment by DaceyTom2** [comment]
I miss-understood how this was being used in the code

**Pull request closed without merging**
