### PR TITLE
VCON-189 Scroll messages on load + on message send

### PR DESCRIPTION
**Pull request by TishamIslam**
### Description
Scrolls messages when the chat window is initially loaded and when new messages are sent. Since it's done in the "onMounted" function, it also scrolls when it's clicked from the inbox. 

### Additional Notes
~~I feel like the way that I did this was sort of "hacky" and maybe not the best way to do it. From what I can tell, the scrollIntoView() function is the proper function to use but I feel like there's a better way to use it than I have.~~

### Issues
Doesn't seem to work on mobile.

### CODE REVIEW

**Comment by neilmispelaar** [comment]
When you hit enter the whole window drops down (on Firefox - not sure if other browsers are behaving differently)

https://user-images.githubusercontent.com/9325038/124367081-4b953300-dc22-11eb-91ba-1f938ebcda85.mov

**Comment by neilmispelaar** [comment]
Here is some code I used in an older project that may be helpful...

https://github.com/Toad-Labs/User-testable-chatbot-prototype/blob/main/src/components/ChatWindowMessages.vue

My strategy was to use `document.querySelector` to get a reference to a dom element, and then use the native javascript attributes to set the `scrolltop` 

```

// Cache the chat message block
 var chatMessagesContainer =  document.querySelector('.my-chat-messages');

chatMessagesContainer.scrollTop = chatMessagesContainer.scrollHeight;

```

One other item that may come up - `vue` takes a few microseconds to update the virtual dom, so if you update `scrollTop` too quickly the dom may not have the new message yet. If this comes up you can do something like the following to wait 50 milliseconds before scrolling down. 

```
// Scroll to the bottom of the container
    setTimeout(function() {
      chatMessagesContainer.scrollTop = chatMessagesContainer.scrollHeight;
    }, 50);
```

`Vue` has a `nextTick` function which basically does the same thing which waits for the dom to be updated - this is faster than waiting a blanket 50 milliseconds, but I can't remember how to use it.

**Comment by TishamIslam** [comment]
> When you hit enter the whole window drops down (on Firefox - not sure if other browsers are behaving differently)
> 
>  drop.mov

Seems to do that on all browsers. I changed it to use scrollTop + scrollHeight like you mentioned and it works like a charm. I just noticed that neither method works properly on mobile, so that's an issue to resolve.

**Review by shewood — COMMENTED** [review]
I tried it on firefox and also chrome and it didn't seem to scroll on message send.

**Review by nibivi77 — COMMENTED** [review]
Tried on Chrome and did not seem to work for me. Any thoughts?

**Review by DaceyTom2 — APPROVED** [review]
Looks super clean and I love the speed

**Pull request merged**
