### PR TITLE
Vcon 172 inbox animation

### PR DESCRIPTION
**Pull request by nibivi77**
### Description

Added animation on mobile when selecting an inbox item.

### Additional Notes

- Test on different browsers please.

### CODE REVIEW

**Comment by DaceyTom2** [comment]
I'm not sure if it is intended that the TextInput component slides in from another direction

**Comment by nibivi77** [comment]
> I'm not sure if it is intended that the TextInput component slides in from another direction

What do you mean?

**Comment by DaceyTom2** [comment]
Sorry, I realised when reproducing that you need to have enough messages for it to be blow the screen. It is probably okay but try adding 10+ messages and then opening up the conversation

**Comment by nibivi77** [comment]
> Sorry, I realised when reproducing that you need to have enough messages for it to be blow the screen. It is probably okay but try adding 10+ messages and then opening up the conversation

You mean it pops up from the bottom up? If that is what you are talking about, it will be fixed in my next PR to "bottom stick" the text input.

**Review by DaceyTom2 — APPROVED** [review]

**Comment by DaceyTom2** [comment]
Tired on Chrome and FF. Very smooth!

**Pull request merged**
