### PR TITLE
Semantic markup for lists instead of divs

### PR DESCRIPTION
**Pull request by DaceyTom2**
### Description
Both the chatbot conversation and email messages now use ul and li tags instead of divs for accessibility reasons

### CODE REVIEW

**Review by TishamIslam — CHANGES_REQUESTED** [review]
Seems like it has the same styling issue as last time, tabbing to the conversation window doesn't give it the focus state. You should pull and re-merge with main (otherwise you might have merge conflicts with the PR I just merged) and add ul to main.css at `div, li {...}` so it becomes `div, li, ul {...}`

**Review by shewood — COMMENTED** [review]
I saw the same as Tisham, you can't tab into the message list anymore.

**Comment by DaceyTom2** [comment]
Good catch, I thought we would be navigating through conversation messages by default but it looks like we hit return to navigate into the conversation messages

**Review by nibivi77 — APPROVED** [review]
Much better! Thank you for this one.

**Review by TishamIslam — APPROVED** [review]
Looks good, everything's in order.

**Pull request merged**
