### PR TITLE
Design fixes

### PR DESCRIPTION
**Pull request by shewood**
Design fixes for: 
vcon-117 - increase the main component height. 
vcon-111 - remove the 1px line
vcon-152 - time stamp font
vcon-156 - component margins on mobile
vcon-181 - inbox spacing

### CODE REVIEW

**Review by TishamIslam — CHANGES_REQUESTED** [review]
vcon-117 - increase the main component height. **Checked, seems good**
vcon-111 - remove the 1px line. **Checked, gone as expected**
vcon-152 - time stamp font. **Font is good, however the size is wrong. See below.**
vcon-156 - component margins on mobile + vcon-181 - inbox spacing; Seems like Thomas already requested changes for them so I'll wait for those

### The Change I am requesting:
In the inspector, the font is listed as 16px but on [Jira](https://decdvirtualconcierge.atlassian.net/browse/VCON-152?atlOrigin=eyJpIjoiYzY4YWZhMGJhY2Y5NDg5NThkNDA5MWQ4NWFkMzZjYmIiLCJwIjoiaiJ9) it's written that it needs to be 14px.
image


Aside from that, great work as usual !

**Comment by shewood** [comment]
Good catch Tisham. I forgot to do the size too.

**Review by DaceyTom2 — APPROVED** [review]

**Comment by DaceyTom2** [comment]
Ahhh finally the favicon change! Love it

**Review by TishamIslam — CHANGES_REQUESTED** [review]
Still need to wait on Thomas' approval on the margin thing, and the feedback button width issue stems from this PR. The latter should be resolved before it's merged, but given that Thomas is off until Tuesday, we can merge and then re-modify these changes if need be.

**Comment by shewood** [comment]
I asked Thomas to put the feedback button changes into a new task.

**Review by TishamIslam — APPROVED** [review]
Okay, that sounds good.

**Pull request merged**
