### PR TITLE
added custom height of 50% viewport

### PR DESCRIPTION
**Pull request by DaceyTom2**
Description

Can now set custom heights in tailwind.
Messages container is leveraging the 1/2 viewport height

### CODE REVIEW

**Review by nibivi77 — APPROVED** [review]
Yes, yes, yes good. Its as good as a purple drift in Mario Kart 8 deluxe.

**Review by TishamIslam — CHANGES_REQUESTED** [review]
I think that it needs to be bigger, the conversation window looks quite short on my screen, maybe something like 75vh would work better?

**Review by shewood — APPROVED** [review]
Looks good

**Comment by neilmispelaar** [comment]
@ThomasFHoy Any opinions on height size of the chat window / inbox

**Review by TishamIslam — APPROVED** [review]

**Pull request merged**
