### PR TITLE
V-CON 133 - Add netlify file with vue config

### PR DESCRIPTION
**Pull request by neilmispelaar**
### Description

- Add the Netlify config `toml` file to address routing issue

### Additional Notes

- [Vue app not routing correctly when deployed](https://answers.netlify.com/t/vue-app-not-routing-correctly-when-deployed/6363)
- [History pushstate and single-page apps](https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps)

### CODE REVIEW

**Comment by neilmispelaar** [comment]
Hmmm, actually in the deploy preview it's not working...

**Comment by neilmispelaar** [comment]
Oh shit - I created a branch from main which means the router file isn't updated with the `fr/en` code.

**Comment by DaceyTom2** [comment]
@neilmispelaar The branch has been pushed

**Comment by neilmispelaar** [comment]
Might be a bug with Github but the PR is still showing as open for me?

**Review by TishamIslam — APPROVED** [review]
Merged it with main, and it works fine now. Good work.

**Comment by shewood** [comment]
Merging this for Neil. I hope that is ok?

**Pull request merged**
