### PR TITLE
Get quick replies/suggested actions from bot into chatoption buttons

### PR DESCRIPTION
**Pull request by TishamIslam**
### Description
Got the suggestedActions thing from the bot, which allows us to use the quick replies given to us by the bot. 

### Additional Notes
At the moment I have it set to default to "Yes" or "No"/"Oui" ou "Non" as the default quick replies if none are sent from the bot.
For testing, at the moment it seems like only the prompt to rate the bot has suggestedActions. So, to test it efficiently, hit the No button. If the prompt gets sent in the wrong order (i.e. it isn't the last message) press No again.

#### Nothing sent by bot so it defaults to Yes/No
image

#### Same thing but en français
image

#### Success!
image

### CODE REVIEW

**Review by nibivi77 — COMMENTED** [review]
this is great Tisham! I think it would be better to not show any suggested answers if none are provided. (hide the buttons)

What do you think?

**Comment by TishamIslam** [comment]
Yup that makes sense, the user can enter yes or no manually anyways.

**Comment by nibivi77** [comment]
> Yup that makes sense, the user can enter yes or no manually anyways.

Exactly, and "Yes" and "no" will most likely be there as suggested actions in the future.

**Review by nibivi77 — APPROVED** [review]
This looks good ! :)

**Pull request merged**
