### PR TITLE
removed links and heading

### PR DESCRIPTION
**Pull request by DaceyTom2**
Description

Removed extra links and heading

Removed "This is the home page" heading from home page
Removed Conversation and Notice links from home page

image

### CODE REVIEW

**Review by TishamIslam — APPROVED** [review]
Looks good, no issues found.

**Review by nibivi77 — COMMENTED** [review]
We could remove the pages inside the views folder as well to clean it up.

**Review by shewood — CHANGES_REQUESTED** [review]
I am not looking at the whole thing but don't we want to keep the <h1> as per Neil's drawing

**Comment by DaceyTom2** [comment]
@shewood We will want a H1. Currently "Inbox" is a H1 but that can be bumped to H2. As for what the H1 should be is left to be designed so I think it would be fair to add it later

**Review by shewood — APPROVED** [review]

**Pull request merged**
